require('options')
require('plugins')

require('colorscheme')
require('lsp')
require('autopairssetup')
require('telescopecfg')
require('debugconfig')
require('keymaps')
require('lualinesetup')
require('conformsetup')
